### PR TITLE
@Presented property wrapper and optimized presentation

### PR DESCRIPTION
**Pull request by rcarver**
Thanks so much for your work on this library! I started using the previous iteration of the project in an app with recursive navigation with frequent effects and found that excessive calls to `.cancellable` and `.cancel` were causing performance issues. I've updated to this new version and really like the changes you made to how cancellation is handled. 

## Summary

This change refines how cancellation occurs in presented states. Both when effects are wrapped n `.cancellable` and when `.cancel` is sent. These effects are fairly costly in TCA [1], and since any action of a presented reducer is wrapped it can really add up.

Additionally, I introduced a `@Presented` property wrapper that allows presentation to be further optimized. To minimize change, the library works with property-wrapped values via `presented` or non-wrapped values via `presents`. The property-wrapped version is better in all cases though.

[1] Perhaps additionally so because they incur a lock. I'm [looking into that](https://github.com/pointfreeco/swift-composable-architecture/discussions/857).

## What was done

- [x] Modify `presents` to only run the child reducer if the action is in the child domain. This reduces unnecessary wrapping with `.cancellable`.
- [x] Add tests for `presents` to confirm how often `.cancel` is sent
- [x] Introduce `presented` variation of `presents` that works with the `@Presented` property wrapper. This version is further optimizes to only `.cancel` when state goes from non-nil to nil. 
- [x] Signification changes to `combine` to enable these changes.

## Review notes

* [ ] It feels like `combine` should not be public. It's a great utility but now very specific to the internals.
* [ ] I couldn't find a cleaner way to assert on calls to cancel, thus the `DEBUG`-only global vars
* [ ] I'm not yet sure how these changes would adapt to `CasePath` presentation
* [ ] The Example should probably be updated to use `@Presented`
* [ ] I'm working on a larger sample of recursive navigation based on this, but it's looking good so far - I'll link it when it's finished. I'm also updating my app, which is looking good but I've yet to fully confirm the performance improvements.

### CODE REVIEW

**Comment by darrarski** [comment]
@rcarver  Thank you for creating the PR! It looks very interesting, and I will definitely review it. Sorry for the lack of my response before, I was offline for a while.

**Comment by rcarver** [comment]
@darrarski all good! Here are two other things I worked on after this PR for your reference:

* https://github.com/rcarver/swift-composable-presentation/pull/1
* https://github.com/rcarver/tca-example-recursive-navigation

**Comment by darrarski** [comment]
@rcarver thanks! That's useful. I appreciate your feedback and support. 

I've also noticed some performance issues and created a draft to address it but never published it. 

My solution is to change the `cancelEffects` closure in `Reducer.combined` function, so it takes two `State` parameters: the state before and after running the reducer. This way, we can check when the state becomes `nil` and only then return `.cancel` effect.

I didn't notice any problems invoking the presented reducer for every action, but perhaps it's just my case.

I love the idea of the property wrapper for the state. I want to make it happen at some point, but I still need to figure it out. I look at `BindableState` property wrapper as an example. It comes with `BindableAction` and `Reducer.binding` extension. Perhaps this should be something that helps model the API nicely. Let me know if you have any thoughts about it.

I've opened #5 with the cancelation improvements mentioned above. I would like to release it in isolation from other changes (like the property wrapper). I would appreciate it if you could check it out and let me know if it reduces the performance impact you've noticed.

**Comment by darrarski** [comment]
While this still seems to be an interesting approach, I decided to close the PR for now. The issues seem to be resolved already by other fixes. Feel free to open a new PR compatible with the latest changes on the `main` branch. Thanks for the support!

**Pull request closed without merging**
